[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "quick-eda-andresbc15"
version = "0.1.0"
description = "Exploratory data analysis helpers to quickly summarize and visualize your data"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Andres Cojuangco" }]
dependencies = ["pandas", "matplotlib"]

[tool.setuptools.packages.find]
where = ["src"]
